version: "3.8"
services:

  netbox-vm-agent:
    image: saashup/netbox-vm-agent:latest
    command: npm start
    volumes:
      - type: volume
        source: netbox-vm-agent
        target: /data
    restart: unless-stopped
    ports:
      - "1880:1880"
    environment:
      - NODE_ENV=prod
      - PORT=1880
      
volumes:
  netbox-vm-agent:
